### PR TITLE
ft: patch http parser to allow slash(/) for headers

### PR DESCRIPTION
**Pull request by rahulreddy**
This patch whitelists slash(/) as an acceptable character for header tokens.

### CODE REVIEW

**Review by bennettbuchanan — APPROVED** [review]

**Review by electrachong — APPROVED** [review]

**Comment by NicolasT** [comment]
I'm a bit confused by this. Does this mean the NodeJS HTTP parser is not standard-compliant, or are we extending it to support something that's not standard-compliant?

If the latter, is this a wise thing to do? Rationale: if we should support non-standard-compliant requests, how can we ensure any service running in front of ours (mainly load balancers, SSL terminators,...) would accept and pass through such requests?

**Comment by alexandre-merle** [comment]
```
/* Tokens as defined by rfc 2616. Also lowercases them.
 *        token       = 1*<any CHAR except CTLs or separators>
 *     separators     = "(" | ")" | "<" | ">" | "@"
 *                    | "," | ";" | ":" | "\" | <">
 *                    | "/" | "[" | "]" | "?" | "="
 *                    | "{" | "}" | SP | HT
 */
```

This part is defined just before the adding of '/' as an allow character, same concern as @NicolasT and here we are expose to undefined behavior / bug / attack because of a custom http protocol. This is really dangerous.
Why do we need such changes ?

**Comment by ghost** [comment]
To add to concerns here, this means we'll have to maintain a fork of this project. We can't really afford to stay wildly outdated considering some of the CVEs that were addressed this year alone, and keeping that maintenance burden won't be funny.

**Comment by LaurenSpiegel** [comment]
yeah, @rahulreddy, how could you suggest such a thing?  😆

**Review by LaurenSpiegel — APPROVED** [review]

**Comment by rahulreddy** [comment]
@NicolasT @alexandre-merle @michael-zapata 

This is a deviation from the RFC to accommodate a customer's request to be inline with our previous product that allowed requests with slashes in header tokens.
When node.js receives a request and if the parser invalidates, it terminates the HTTP connection early, we do not even get a request listener to log the invalid request. After trying to figure out how to fix this, we have no other way other than patching `http_parser.c` for incoming requests and `_http_common.js` for responses. Everyone of us share the similar concerns of how bad it could be by deviating from the RFC, maintainability of our custom node version but it has to be done.

We came up with the idea of limiting its exposure by
- enabling/disabling the deviation through an env var or config
- limiting the scope of headers allowed with slashes to x-* only on the application level (S3)
- Since we use exact version of node.js for deployments, it's a manual task but fairly feasible given that the parser don't get as many updates as the other core modules do. We will be generating tar ball installer the using the bundled scripts and deploy it the same way as we currently do.
- We will also gain control over sending the correct error responses to the clients from S3 which is viewed as an incompatibility otherwise.

This configuration will be disabled by default in our deployments at the customers' sites. If it has to be enabled the customer will be made fully aware of the risk of sending non-rfc HTTP requests to load balancers/proxies with the possibility of helping them validate the requests during the deployment.

**Comment by GiorgioRegni** [comment]
Thanks @rahulreddy you summed it up perfectly. Indeed the customer is against the wall and we've looked at many options before going with this one.

**Review by electrachong — APPROVED** [review]

**Review by bennettbuchanan — APPROVED** [review]

**Comment by NicolasT** [comment]
Given that `http_parser_execute` is not static, did you consider using an `LD_PRELOAD` and using it selectively instead of shipping a fully custom NodeJS distribution?

**Comment by GiorgioRegni** [comment]
Damn that's a good point, thanks for pointing it out @NicolasT

**Comment by LaurenSpiegel** [comment]
We would still have to deal with the javascript change though for outgoing, correct?  Unless the customer is ok with translating the outgoing into something compliant.

**Comment by NicolasT** [comment]
Monkey-patch during start-up?

**Comment by LaurenSpiegel** [comment]
It's not very pretty.  This was a quick go at it -- https://github.com/scality/S3/pull/461

**Comment by NicolasT** [comment]
@LaurenSpiegel I meant only monkey-patching the `checkIsHttpToken` method (which seems to be the only one touched in this PR). This seems not to be possible without copying it completely though, which may be OK in this case since (given the thing being based on a spec), its functionality/behaviour shouldn't change over time.
Another option would be to monkey-patch it with a function which creates a copy of the input, replacing all /'s with some known-to-be-valid character, and feeding that to the original implementation, though that may be quite a bit less efficient.

**Pull request merged**
